# Generated by Django 5.2.3 on 2025-07-01 01:50

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gamepass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("price", models.CharField(max_length=100, verbose_name="Цена")),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "gamepass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="main.gamepass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=1000, verbose_name="Имя")),
                (
                    "balance",
                    models.CharField(
                        default="0", max_length=100, verbose_name="Баланс"
                    ),
                ),
                (
                    "referral_id",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Код друга"
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        default=main.models.generate_referral_code,
                        max_length=100,
                        unique=True,
                        verbose_name="Код для друга",
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        blank=True, related_name="owners", to="main.place"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_places",
                to="main.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="gamepass",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamepasses",
                to="main.userprofile",
            ),
        ),
    ]
