# Generated by Django 3.2.8 on 2025-07-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID аккаунта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(default=1, max_length=500, verbose_name='Аватарка аккаунта'),
            preserve_default=False,
        ),
    ]
