# Generated by Django 5.2.3 on 2025-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250701_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_balance',
            field=models.CharField(default='0', max_length=100, verbose_name='Баланс'),
        ),
    ]
