# Generated by Django 5.2.4 on 2025-07-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="main.userprofile",
                verbose_name="Пригласивший",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="main.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вывод",
                "verbose_name_plural": "Заявки на вывод",
            },
        ),
    ]
