# Generated by Django 5.2.4 on 2025-07-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_userprofile_referrer_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reward_reviews",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reward_telegram",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reward_vk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reward_youtube",
            field=models.BooleanField(default=False),
        ),
    ]
