# Generated by Django 5.2.4 on 2025-07-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userprofile_reward_reviews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
    ]
