# Generated by Django 5.2.4 on 2025-07-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_userprofile_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("completed", "Выполнено"),
                    ("error", "Ошибка"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
